/* WARNING! All changes made to this file will be lost! */

#ifndef W_CONFIG_H_WAF
#define W_CONFIG_H_WAF

#define DEFAULT_DVD_DEVICE "D:"
#define DEFAULT_CDROM_DEVICE "D:"
#define HAVE_LGPL 0
#define HAVE_GPL 1
#define HAVE_LIBAF 0
#define HAVE_CPLAYER 1
#define HAVE_LIBMPV_SHARED 1
#define HAVE_LIBMPV_STATIC 0
#define HAVE_STATIC_BUILD 0
#define HAVE_BUILD_DATE 1
#define HAVE_OPTIMIZE 1
#define HAVE_DEBUG_BUILD 1
#define HAVE_MANPAGE_BUILD 0
#define HAVE_HTML_BUILD 0
#define HAVE_PDF_BUILD 0
#define HAVE_LIBDL 0
#define HAVE_CPLUGINS 0
#define HAVE_ZSH_COMP 0
#define HAVE_ASM 1
#define HAVE_TEST 0
#define HAVE_CLANG_DATABASE 0
#define HAVE_NOEXECSTACK 1
#define HAVE_LIBM 0
#define HAVE_MINGW 0
#define HAVE_POSIX 0
#define HAVE_ANDROID 0
#define HAVE_EGL_ANDROID 0
#define HAVE_POSIX_OR_MINGW 1
#define HAVE_SWIFT 0
#define HAVE_UWP 0
#define HAVE_WIN32_DESKTOP 1
#define HAVE_WIN32_INTERNAL_PTHREADS 1
#define HAVE_PTHREADS 0
#define HAVE_GNUC 0
#define HAVE_STDATOMIC 1
#define HAVE_ATOMICS 1
#define HAVE_LIBRT 0
#define HAVE_ICONV 0
#define HAVE_DOS_PATHS 1
#define HAVE_POSIX_SPAWN_NATIVE 0
#define HAVE_POSIX_SPAWN_ANDROID 0
#define HAVE_POSIX_SPAWN 0
#define HAVE_WIN32_PIPES 1
#define HAVE_GLOB_POSIX 0
#define HAVE_GLOB_WIN32 1
#define HAVE_GLOB 1
#define HAVE_FCHMOD 0
#define HAVE_VT_H 0
#define HAVE_GBM_H 0
#define HAVE_GLIBC_THREAD_NAME 0
#define HAVE_OSX_THREAD_NAME 0
#define HAVE_BSD_THREAD_NAME 0
#define HAVE_BSD_FSTATFS 0
#define HAVE_LINUX_FSTATFS 0
#define HAVE_LIBSMBCLIENT 0
#define HAVE_LUA 0
#define HAVE_51DEB 0
#define HAVE_JAVASCRIPT 0
#define HAVE_LIBASS 0
#define HAVE_LIBASS_OSD 0
#define HAVE_DUMMY_OSD 0
#define HAVE_ZLIB 1
#define HAVE_LIBBLURAY 0
#define HAVE_DVDREAD 0
#define HAVE_DVDNAV 0
#define HAVE_DVDREAD_COMMON 0
#define HAVE_CDDA 0
#define HAVE_UCHARDET 0
#define HAVE_RUBBERBAND 0
#define HAVE_LCMS2 0
#define HAVE_VAPOURSYNTH 0
#define HAVE_VAPOURSYNTH_LAZY 0
#define HAVE_VAPOURSYNTH_CORE 0
#define HAVE_LIBARCHIVE 0
#define HAVE_SDL2 0
#define HAVE_OSS_AUDIO 0
#define HAVE_RSOUND 0
#define HAVE_SNDIO 0
#define HAVE_PULSE 0
#define HAVE_JACK 0
#define HAVE_OPENAL 0
#define HAVE_OPENSLES 0
#define HAVE_ALSA 0
#define HAVE_COREAUDIO 0
#define HAVE_AUDIOUNIT 0
#define HAVE_WASAPI 1
#define HAVE_COCOA 0
#define HAVE_DRM 0
#define HAVE_DRMPRIME 1
#define HAVE_GBM 0
#define HAVE_WAYLAND_SCANNER 0
#define HAVE_WAYLAND_PROTOCOLS 0
#define HAVE_WAYLAND 0
#define HAVE_X11 0
#define HAVE_XV 0
#define HAVE_GL_COCOA 0
#define HAVE_GL_X11 0
#define HAVE_EGL_X11 0
#define HAVE_EGL_DRM 0
#define HAVE_GL_WAYLAND 0
#define HAVE_GL_WIN32 1
#define HAVE_GL_DXINTEROP 1
#define HAVE_EGL_ANGLE 0
#define HAVE_EGL_ANGLE_LIB 0
#define HAVE_EGL_ANGLE_WIN32 0
#define HAVE_VDPAU 0
#define HAVE_VDPAU_GL_X11 0
#define HAVE_VAAPI 0
#define HAVE_VAAPI_X11 0
#define HAVE_VAAPI_WAYLAND 0
#define HAVE_VAAPI_DRM 0
#define HAVE_VAAPI_GLX 0
#define HAVE_VAAPI_X_EGL 0
#define HAVE_VAAPI_EGL 0
#define HAVE_CACA 0
#define HAVE_JPEG 0
#define HAVE_DIRECT3D 1
#define HAVE_SHADERC_SHARED 0
#define HAVE_SHADERC_STATIC 0
#define HAVE_SHADERC 1
#define HAVE_CROSSC 1
#define HAVE_D3D11 1
#define HAVE_RPI 0
#define HAVE_IOS_GL 0
#define HAVE_PLAIN_GL 1
#define HAVE_MALI_FBDEV 0
#define HAVE_GL 1
#define HAVE_LIBPLACEBO 0
#define HAVE_VULKAN 0
#define HAVE_EGL_HELPERS 1
#define HAVE_LIBAVCODEC 1
#define HAVE_FFMPEG 1
#define HAVE_LIBAV 0
#define HAVE_LIBAV_ANY 1
#define HAVE_LIBAVDEVICE 1
#define HAVE_VIDEOTOOLBOX_HWACCEL 0
#define HAVE_VIDEOTOOLBOX_GL 0
#define HAVE_D3D_HWACCEL 1
#define HAVE_D3D9_HWACCEL 1
#define HAVE_GL_DXINTEROP_D3D9 1
#define HAVE_FFNVCODEC 0
#define HAVE_CUDA_HWACCEL 0
#define HAVE_TV 0
#define HAVE_SYS_VIDEOIO_H 0
#define HAVE_VIDEODEV 0
#define HAVE_TV_V4L2 0
#define HAVE_LIBV4L2 0
#define HAVE_AUDIO_INPUT 0
#define HAVE_DVBIN 0
#define HAVE_APPLE_REMOTE 0
#define HAVE_MACOS_TOUCHBAR 0
#define HAVE_MACOS_COCOA_CB 0
#define CONFIGURATION "waf configure CC=gcc.exe --check-c-compiler=gcc --prefix=/mingw32 --enable-libmpv-shared --enable-lua --enable-libass --enable-libbluray --enable-uchardet --disable-win32-internal-pthreads --disable-vapoursynth --disable-vapoursynth-lazy --disable-x11 --disable-wayland-scanner --disable-wayland --disable-wayland-protocols --disable-pulse --disable-jack --disable-alsa --disable-libplacebo --disable-crossc --disable-manpage-build"
//#define MPV_CONFDIR "/mingw32/etc/mpv"
#define FULLCONFIG "51deb asm atomics build-date caca cplayer cuda-hwaccel d3d-hwaccel d3d9-hwaccel debug-build direct3d dos-paths drmprime egl-angle egl-angle-win32 egl-helpers ffmpeg ffnvcodec gl gl-dxinterop gl-dxinterop-d3d9 gl-win32 glibc-thread-name glob glob-win32 gnuc gpl iconv javascript jpeg lcms2 libaf libarchive libass libass-osd libav-any libavcodec libavdevice libbluray libm libmpv-shared lua mingw noexecstack optimize plain-gl posix-or-mingw pthreads rubberband stdatomic uchardet wasapi win32-desktop win32-pipes zlib"

#endif /* W_CONFIG_H_WAF */
